version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: basedcollective
      POSTGRES_PASSWORD: basedcollective
      POSTGRES_DB: basedcollective
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
