export const NOTIFICATION_EVENT_TYPES = {
  REPLY_TO_POST: 'REPLY_TO_POST',
  REPLY_TO_COMMENT: 'REPLY_TO_COMMENT',
  UPVOTE_ON_POST: 'UPVOTE_ON_POST',
  UPVOTE_ON_COMMENT: 'UPVOTE_ON_COMMENT',
  POST_APPROVED: 'POST_APPROVED',
  POST_REJECTED: 'POST_REJECTED',
  ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
  APPEAL_OUTCOME: 'APPEAL_OUTCOME',
  REFERRAL_CODE_USED: 'REFERRAL_CODE_USED',
  REFERRED_USER_ACCEPTED: 'REFERRED_USER_ACCEPTED',
  WORLDCOIN_LAPSE_WARNING: 'WORLDCOIN_LAPSE_WARNING',
  SYSTEM_ANNOUNCEMENT: 'SYSTEM_ANNOUNCEMENT',
} as const;
